import { meta, shopify, starbucks, tesla } from "../assets/images";
import {
  car,
  contact,
  css,
  estate,
  express,
  git,
  github,
  html,
  javascript,
  linkedin,
  mongodb,
  nodejs,
  pricewise,
  react,
  redux,
  sass,
  snapgram,
  summiz,
  tailwindcss,
  threads,
  typescript,
  vue,
  pinia,
  nuxt,
  soporte,
  henry,
  btp,
  gcf,
  spotify,
  pokemon,
  rick,
  batatabit,
  calendar,
  country,
  cart,
  food,
  house,
  trivia,
} from "../assets/icons";

export const skills = [
  {
    imageUrl: html,
    name: "HTML 5",
    type: "Frontend",
  },
  {
    imageUrl: css,
    name: "CSS 3",
    type: "Frontend",
  },
  {
    imageUrl: javascript,
    name: "JavaScript",
    type: "Frontend",
  },
  {
    imageUrl: typescript,
    name: "TypeScript",
    type: "Frontend",
  },
  {
    imageUrl: react,
    name: "React",
    type: "Frontend",
  },
  {
    imageUrl: redux,
    name: "Redux",
    type: "State Management",
  },
  {
    imageUrl: vue,
    name: "Vue JS",
    type: "Frontend",
  },
  {
    imageUrl: pinia,
    name: "Pinia",
    type: "Frontend",
  },
  {
    imageUrl: nuxt,
    name: "Nuxt 3",
    type: "Frontend",
  },
  {
    imageUrl: sass,
    name: "SASS",
    type: "Frontend",
  },
  {
    imageUrl: tailwindcss,
    name: "Tailwind CSS",
    type: "Frontend",
  },
  {
    imageUrl: mongodb,
    name: "MongoDB",
    type: "Database",
  },
  {
    imageUrl: nodejs,
    name: "Node.js",
    type: "Backend",
  },
  {
    imageUrl: express,
    name: "Express",
    type: "Backend",
  },
  {
    imageUrl: git,
    name: "Git",
    type: "Version Control",
  },
  {
    imageUrl: github,
    name: "GitHub",
    type: "Version Control",
  },
];

export const experiences = [
  {
    id: "soporte",
    title: "IT Support Specialist",
    company_name: "Soporte S.A",
    icon: soporte,
    iconBg: "#2b122b",
  },
  {
    id: "henryTA",
    title: "Bootcamp Assistant (TA) for Full-Stack Development students",
    company_name: "Henry",
    icon: henry,
    iconBg: "#000",
  },
  {
    id: "btp",
    title: "FullStack Developer",
    company_name: "BTP Aquaforjas",
    icon: btp,
    iconBg: "#123247",
  },
  {
    id: "gcf",
    title: "Frontend Developer",
    company_name: "GCF AprendeLibre",
    icon: gcf,
    iconBg: "#FFF",
  },
];

export const socialLinks = [
  {
    name: "Contact",
    iconUrl: contact,
    link: "/contact",
  },
  {
    name: "GitHub",
    iconUrl: github,
    link: "https://github.com/YourGitHubUsername",
  },
  {
    name: "LinkedIn",
    iconUrl: linkedin,
    link: "https://www.linkedin.com/in/YourLinkedInUsername",
  },
];

export const projects = [
  {
    id: "spotifu",
    iconUrl: spotify,
    theme: "btn-back-red",
    name: "Spotifu",
    link: "https://github.com/babaquero07/Spotifu",
  },
  {
    id: "pokemon",
    iconUrl: pokemon,
    theme: "btn-back-yellow",
    name: "Pokemon Static",
    link: "https://github.com/babaquero07/pokemon-static-NextJS",
  },
  {
    id: "rickandmorty",
    iconUrl: rick,
    theme: "btn-back-blue",
    name: "Rick and Morty - Vanilla JS",
    link: "https://github.com/babaquero07/taller-unidad-1-2",
  },
  {
    id: "batatabit",
    iconUrl: batatabit,
    theme: "btn-back-pink",
    name: "BatataBit",
    link: "https://github.com/babaquero07/batata-bit",
  },
  {
    id: "calendar",
    iconUrl: calendar,
    theme: "btn-back-black",
    name: "Calendar",
    link: "https://github.com/babaquero07/calendario",
  },
  {
    id: "countrysearch",
    iconUrl: country,
    theme: "btn-back-red",
    name: "Country Search",
    link: "https://github.com/babaquero07/country-search",
  },
  {
    id: "ecommerce",
    iconUrl: cart,
    theme: "btn-back-pink",
    name: "E-commerce",
    link: "https://www.linkedin.com/posts/carla-faes_buenas-tardes-quiero-compartirles-el-video-ugcPost-6920831465534427136-VD5k/?utm_source=share&utm_medium=member_desktop",
  },
  {
    id: "foodrecipes",
    iconUrl: food,
    theme: "btn-back-yellow",
    name: "Food Recipes",
    link: "https://food-recipes-one.vercel.app/",
  },
  {
    id: "inmobilapp",
    iconUrl: house,
    theme: "btn-back-blue",
    name: "InmobilApp",
    link: "https://github.com/InmobilApp",
  },
  {
    id: "triviachallenge",
    iconUrl: trivia,
    theme: "btn-back-red",
    name: "Trivia Challenge",
    link: "https://github.com/babaquero07/trivia-challenge-client",
  },
];
